// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Advantage: typeof import('./src/components/Advantage.vue')['default']
    Circle: typeof import('./src/components/Progress/Circle.vue')['default']
    ContactUs: typeof import('./src/components/Drawer/ContactUs.vue')['default']
    Drawer: typeof import('./src/components/Plant/Drawer.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    FirstScreen: typeof import('./src/components/FirstScreen.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Images: typeof import('./src/components/images/index.vue')['default']
    Introduction: typeof import('./src/components/Introduction.vue')['default']
    LeaveMessage: typeof import('./src/components/LeaveMessage.vue')['default']
    NumberGrow: typeof import('./src/components/NumberGrow/index.vue')['default']
    PreImg: typeof import('./src/components/PreImg/index.vue')['default']
    Preview: typeof import('./src/components/images/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
